taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeleteView,
    car_add_driver_view,
    car_delete_driver_view
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list"
    ),
    path(
        "manufacturers/create/",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create"
    ),
    path(
        "manufacturers/<int:pk>/update/",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update"
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete"
    ),
    path(
        "cars/",
        CarListView.as_view(),
        name="car-list"
    ),
    path(
        "cars/<int:pk>/",
        CarDetailView.as_view(),
        name="car-detail"
    ),
    path(
        "cars/create/",
        CarCreateView.as_view(),
        name="car-create"
    ),
    path(
        "cars/<int:pk>/update/",
        CarUpdateView.as_view(),
        name="car-update"
    ),
    path(
        "cars/<int:pk>/delete/",
        CarDeleteView.as_view(),
        name="car-delete"
    ),
    path(
        "cars/<int:pk>/add-user-to-drivers/",
        car_add_driver_view,
        name="car-add-driver"
    ),
    path(
        "cars/<int:pk>/delete-user-from-drivers/",
        car_delete_driver_view,
        name="car-delete-driver"),
    path(
        "drivers/",
        DriverListView.as_view(),
        name="driver-list"
    ),
    path(
        "drivers/<int:pk>/",
        DriverDetailView.as_view(),
        name="driver-detail"
    ),
    path(
        "drivers/create/",
        DriverCreateView.as_view(),
        name="driver-create"
    ),
    path(
        "drivers/<int:pk>/update/",
        DriverUpdateView.as_view(),
        name="driver-update"
    ),
    path(
        "drivers/<int:pk>/delete/",
        DriverDeleteView.as_view(),
        name="driver-delete"
    ),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model

taxi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from taxi.models import Driver, Car


def validate_license_number(license_number):
    if len(license_number) != 8:
        raise ValidationError("License must consist only of 8 characters")
    elif not license_number[:3].isupper() or not license_number[:3].isalpha():
        raise ValidationError("First 3 characters must be uppercase letters")
    elif not license_number[3:].isdigit():
        raise ValidationError("Last 5 characters must be digits")
    return license_number


class DriverCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Driver
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "license_number")

    def clean_license_number(self):
        return validate_license_number(self.cleaned_data["license_number"])


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ("license_number",)

    def clean_license_number(self):
        return validate_license_number(self.cleaned_data["license_number"])


class CarForm(forms.ModelForm):
    drivers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Car
        fields = "__all__"


class DriverSearchForm(forms.Form):
    search = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import DriverCreationForm, DriverForm, CarForm, DriverSearchForm
from .models import Driver, Car, Manufacturer


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 5


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    success_url = reverse_lazy("taxi:manufacturer-list")


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 5
    queryset = Car.objects.all().select_related("manufacturer")


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("taxi:car-list")


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    success_url = reverse_lazy("taxi:car-list")


def car_add_driver_view(request, pk):
    Car.objects.get(pk=pk).drivers.add(request.user)
    return HttpResponseRedirect(reverse("taxi:car-detail", kwargs={'pk': pk}))


def car_delete_driver_view(request, pk):
    Car.objects.get(pk=pk).drivers.remove(request.user)
    return HttpResponseRedirect(reverse("taxi:car-detail", kwargs={'pk': pk}))


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 5
    queryset = Driver.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DriverListView, self).get_context_data(**kwargs)

        search = self.request.GET.get("search", "")

        context["search_form"] = DriverSearchForm(initial={"search": search})

        return context

    def get_queryset(self):
        form = DriverSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["search"]
            )

        return self.queryset


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    success_url = reverse_lazy("taxi:driver-list")

templates/taxi/car_confirm_delete.html
{% extends "base.html" %}

{% block title %}
   <title>Delete Car</title>
{% endblock %}

{% block content %}
    <h1>Delete Car</h1>

    <p>Are you sure you want to delete car:
        <strong>"{{ car.model }}" {{ car.manufacturer.name }}</strong></p>

    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" value="Yes, delete" class="btn btn-primary">
        <a href="{% url 'taxi:car-detail' pk=car.id %}" class="btn btn-primary">No</a>
    </form>
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block title %}
   <title> Car info</title>
{% endblock %}

{% block content %}
    <h1>Model: {{ car.model }}</h1>
    <p>Manufacturer: ({{ car.manufacturer.name }}, {{ car.manufacturer.country }})</p>
    {% if car in user.cars.all %}
        <a href="{% url 'taxi:car-delete-driver' pk=car.id %}" class="btn btn-primary">Delete me from this car</a>
    {% else %}
        <a href="{% url 'taxi:car-add-driver' pk=car.id %}" class="btn btn-primary">Assign me to this car</a>
    {% endif %}
    <hr>
    <h4>Drivers:</h4>
    <ul>
    {% for driver in car.drivers.all %}
        <li>
            {{ driver.username }}
            {% if driver.first_name %}
                ({{ driver.first_name }} {{ driver.last_name }})
            {% endif %}
            {% if driver == user %}
                (Me)
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    <p>
        <a href="{% url 'taxi:car-update' pk=car.id %}" class="btn btn-primary"> Update car</a>
        <a href="{% url 'taxi:car-delete' pk=car.id %}" class="btn btn-primary"> Delete car</a>
    </p>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title> {{ object|yesno:"Update, Create" }} car </title>
{% endblock %}

{% block content %}
    <h1> {{ object|yesno:"Update, Create" }} car </h1>
    <hr>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}

{% block title %}
   <title>Car list</title>
{% endblock %}

{% block content %}
    <h1>Car list</h1>
    <h4><a class="btn btn-primary" href="{% url 'taxi:car-create' %}">Create car</a></h4>
    {% if car_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Model</th>
        <th>Manufacturer name</th>
        <th>Manufacturer country</th>
      </tr>
    {% for car in car_list %}
      <tr>
        <td>{{ car.id }}</td>
        <td><a class="text-ref" href="{{ car.id }}">{{ car.model }}</a></td>
        <td>{{ car.manufacturer.name }}</td>
        <td>{{ car.manufacturer.country }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
        <p>There are no cars in taxi</p>
    {% endif %}
{% endblock %}

templates/taxi/driver_confirm_delete.html
{% extends "base.html" %}

{% block title %}
   <title>Delete driver</title>
{% endblock %}

{% block content %}
    <h1>Delete driver</h1>
    <hr>
    <p>Are you sure you want to delete driver: <strong>{{ driver.username }} </strong></p>
    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" value="Yes, delete" class="btn btn-primary">
        <a href="{% url 'taxi:driver-detail' pk=driver.id %}" class="btn btn-primary">No</a>
    </form>
{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block title %}
   <title>Driver info</title>
{% endblock %}

{% block content %}
    <h2>Username: <strong>{{ driver.username }}</strong></h2>
    <a href="{% url 'taxi:driver-update' pk=driver.id %}" class="btn btn-primary"> Update license</a>
    <a href="{% url 'taxi:driver-delete' pk=driver.id %}" class="btn btn-primary"> Delete driver</a>
    <hr>
    <p><strong>First name:</strong> {{ driver.first_name }}</p>
    <p><strong>Last name:</strong> {{ driver.last_name }}</p>
    <p><strong>License number:</strong> {{ driver.license_number }}</p>
    <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

    <div class="ml-3">
    <h3>Cars:</h3>
    <hr>
    {% for car in driver.cars.all %}
        <p>- "{{ car.model }}" {{ car.manufacturer.name }} ({{ car.manufacturer.country }})</p>
    {% empty %}
      <p>No cars!</p>
    {% endfor %}
    </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title>{{ object|yesno:"Update, Create" }} driver</title>
{% endblock %}

{% block content %}
    <h1> {{ object|yesno:"Update, Create" }} driver </h1>
    <br>

    <form action="" method="post" novalidate >
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title>Driver list</title>
{% endblock %}

{% block content %}
    <h1>Driver list</h1>
    <hr>
    <p><a href="{% url 'taxi:driver-create' %}" class="btn btn-primary"> Create driver</a></p>
    <form action="" method="get" class="form-inline">
      {% csrf_token %}
      {{ search_form|crispy}}
      <input class="btn btn-secondary" type="submit" value="🔎">
    </form>
    {% if driver_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
      </tr>
    {% for driver in driver_list %}
      <tr>
        <td>{{ driver.id }}</td>
        <td><a class="text-ref" href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a></td>
        <td>{{ driver.first_name }}</td>
        <td>{{ driver.last_name }}</td>
        <td>{{ driver.license_number }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}

<img class="img-sidebar" src="https://image.shutterstock.com/image-vector/magnifier-glass-icon-logo-template-600w-1437502985.jpg" alt="">

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <hr>
    <p>Welcome to Best Taxi Ever!</p>
    <br>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>
    <br>

    <i><p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p></i>
{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html" %}

{% block title %}
   <title>Delete Manufacturer</title>
{% endblock %}

{% block content %}
    <h1>Delete Manufacturer</h1>

    <p>Are you sure you want to delete manufacturer:
        <strong>"{{ manufacturer.name }}" ({{ manufacturer.country }})</strong></p>
    <p>All cars with this manufacturer will be also deleted!</p>

    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" value="Yes, delete" class="btn btn-primary">
        <a href="{% url 'taxi:manufacturer-list' %}" class="btn btn-primary">No</a>
    </form>
{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title>{{ object|yesno:"Update, Create" }} manufacturer</title>
{% endblock %}

{% block content %}
    <h1> {{ object|yesno:"Update, Create" }} manufacturer </h1>
    <hr>

    <form action="" method="post" novalidate >
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block title %}
   <title>Manufacturer list</title>
{% endblock %}

{% block content %}
    <h1>Manufacturer list
    </h1>
    <h4><a class="btn btn-primary" href="{% url 'taxi:manufacturer-create' %}"> Create manufacturer</a></h4>

    {% if manufacturer_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Country</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for manufacturer in manufacturer_list %}
            <tr>
              <td>
                  {{ manufacturer.id }}
              </td>
              <td>
                  {{ manufacturer.name }}
              </td>
              <td>
                  {{ manufacturer.country }}
              </td>
              <td>
                  <a class="text-ref" href="{% url 'taxi:manufacturer-update' pk=manufacturer.id %}"> Update </a>
              </td>
              <td>
                  <a class="text-ref" href="{% url 'taxi:manufacturer-delete' pk=manufacturer.id %}"> Delete </a>
              </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no manufacturers in the service.</p>
    {% endif %}
{% endblock %}