taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeleteView,
    car_add_driver_view,
    car_delete_driver_view
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list"
    ),
    path(
        "manufacturers/create/",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create"
    ),
    path(
        "manufacturers/<int:pk>/update/",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update"
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete"
    ),
    path(
        "cars/",
        CarListView.as_view(),
        name="car-list"
    ),
    path(
        "cars/<int:pk>/",
        CarDetailView.as_view(),
        name="car-detail"
    ),
    path(
        "cars/create/",
        CarCreateView.as_view(),
        name="car-create"
    ),
    path(
        "cars/<int:pk>/update/",
        CarUpdateView.as_view(),
        name="car-update"
    ),
    path(
        "cars/<int:pk>/delete/",
        CarDeleteView.as_view(),
        name="car-delete"
    ),
    path(
        "cars/<int:pk>/add-user-to-drivers/",
        car_add_driver_view,
        name="car-add-driver"
    ),
    path(
        "cars/<int:pk>/delete-user-from-drivers/",
        car_delete_driver_view,
        name="car-delete-driver"),
    path(
        "drivers/",
        DriverListView.as_view(),
        name="driver-list"
    ),
    path(
        "drivers/<int:pk>/",
        DriverDetailView.as_view(),
        name="driver-detail"
    ),
    path(
        "drivers/create/",
        DriverCreateView.as_view(),
        name="driver-create"
    ),
    path(
        "drivers/<int:pk>/update/",
        DriverUpdateView.as_view(),
        name="driver-update"
    ),
    path(
        "drivers/<int:pk>/delete/",
        DriverDeleteView.as_view(),
        name="driver-delete"
    ),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item sidebar-col">
        <a class="text-col img-user" href="{{ user.get_absolute_url }}">
            <img class="img-sidebar" src="https://cdn-icons-png.flaticon.com/512/23/23171.png" alt="">
            {{ user.get_username }}</a></li>
    <li class="list-group-item sidebar-col">
        <a class="text-col" href="{% url 'logout'%}?next={{request.path}}">
            <img class="img-sidebar" src="https://img.icons8.com/ios-filled/344/exit-sign.png" alt="">
            Logout</a></li>
  {% else %}
    <li class="list-group-item sidebar-col"><a class="text-col" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item sidebar-col"><a class="text-col" href="{% url 'taxi:index' %}">Home</a></li>
  <li class="list-group-item sidebar-col"><a class="text-col" href="{% url 'taxi:driver-list' %}">All drivers</a></li>
  <li class="list-group-item sidebar-col"><a class="text-col" href="{% url 'taxi:car-list' %}">All cars</a></li>
  <li class="list-group-item sidebar-col"><a class="text-col" href="{% url 'taxi:manufacturer-list' %}">All manufacturers</a></li>
</ul>